version: "3.9"

services:
  api:
    image: v1dkos/django-api-p32:latest
    container_name: django-api-p32
    ports:
      - "4512:8000"
  front:
    image: v1dkos/django-frontend:latest
    #build:

    container_name: react_front
    ports:
      - "4518:80"